
# Comment/uncomment the following line to disable/enable debugging 
# DEBUG = y 
# # Add your debugging flag (or not) to CFLAGS 
# ifeq ($(DEBUG),y) 
#   DEBFLAGS = -O -g -DSCULL_DEBUG 
# # "-O" is needed to expand inlines 
# else 
#   DEBFLAGS = -O2 
# endif 
#DEBFLAGS = -O -g -D SCULL_DEBUG 
obj-m := ppsInterrupt.o
#pid-objs := pidyeboPPS.o ad5362.o ad7367.o crc_gen.o max7301.o
pps-objs := ppsInterrupt.o 






